Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

1. Logistic Regression
2. SVM
3. Decision Tree
4. Random Forest

In [115]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [116]:
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [117]:
list(iris.target_names)

['setosa', 'versicolor', 'virginica']

In [118]:
df = pd.DataFrame(data = iris.data, columns=iris.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [119]:
df['target'] = iris.target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [120]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [121]:
X = df.drop('target', axis='columns')
y = df['target']

In [122]:
scores_lr = cross_val_score(LogisticRegression(max_iter=1000), X, y, cv=3)
scores_lr

array([0.98, 0.96, 0.98])

In [123]:
np.average(scores_lr)

0.9733333333333333

In [124]:
scores_svm = cross_val_score(SVC(), X, y, cv=3)
scores_svm

array([0.96, 0.98, 0.94])

In [125]:
np.average(scores_svm)

0.96

In [126]:
scores_dt = cross_val_score(DecisionTreeClassifier(), X, y, cv=3)
scores_dt

array([0.98, 0.94, 1.  ])

In [127]:
np.average(scores_dt)

0.9733333333333333

In [128]:
scores_rf = cross_val_score(RandomForestClassifier(n_estimators=50), X, y, cv=3)
scores_rf

array([0.98, 0.94, 0.96])

In [129]:
np.average(scores_rf)

0.96

1. LR => 97.33
2. SVC => 96
3. DT => 97.33
4. RF => 96